### ISSUE TITLE
spineGeneric dataset: issues

### ISSUE THREAD

**Issue by charleygros** [ivadomed/ivadomed#21]
Please find herebelow issues observed in the dataset `spineGeneric`.

Data folder: `../duke/projects/ivado-medical-imaging/spineGeneric_201907041011/result/`.

Issues will be ticked once resolved.

### Todo -- Version `spineGeneric_201907041011` -- 2019-09-05:

Files with no metadata:
- [x] sub-unf02_T2star.nii.gz
- [x] sub-balgrist02_T2star.nii.gz
- [x] sub-barcelona01_T2star.nii.gz
- [x] sub-hamburg01_T2star.nii.gz
- [x] sub-mgh01_T2star.nii.gz
- [x] sub-mgh02_T2star.nii.gz
- [x] sub-mgh06_T2star.nii.gz
- [x] sub-mniPilot1_T2star.nii.gz
- [x] sub-mniS02_T2star.nii.gz
- [x] sub-mniS05_T2star.nii.gz
- [x] sub-nottwil05_T2star.nii.gz
- [x] sub-nwu03_T2star.nii.gz
- [x] sub-nwu04_T2star.nii.gz
- [x] sub-oxfordFmrib03_T2star.nii.gz
- [x] sub-oxfordFmrib05_T2star.nii.gz
- [x] sub-oxfordFmrib06_T2star.nii.gz
- [x] sub-tehranS03_T2star.nii.gz
- [x] sub-hamburg04_T2star.nii.gz
- [x] sub-oxfordOhba04_T2star.nii.gz

### Todo -- Old version `spineGeneric_201904271322` --> Charley will check if still relevant:

Data involved `nan` values during the training, unknown reason
- [ ] unf

T2star image is 4D:
- [ ] vuiis-achieva
- [ ] vuiis-ingenia

### DONE:

Remove final comma in `dataset_description.json`:
- [x]     mgh
- [x]     brno-prisma
- [x]     hamburg
- [x]     geneva
- [x]     vuiis-achieva
- [x]     vuiis-ingenia
- [x]     queensland

Remove the useless { and } in `dataset_description.json`:
- [x] queensland

Multiple echo times in the json file:
- [x] ucl

**Comment by alexfoias** [comment]
@charleygros Do we still have to address this issue ?

**Comment by charleygros** [comment]
All good now, thanks @alexfoias
